import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/ui-components/styles/Home.module.css";
import { MortgageForm } from "@/ui-components/mortgage-form";


const inter = Inter({ subsets: ["latin"] });
const headerColor = {
  color: "#D8546D"
}

export default function Home() {
  return (
    <>
      <Head>
        <meta charSet="utf-8"/>
        <title>Calculadora de Amortização</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container ${inter.className}`}>
        <h1 style={headerColor}>Calculadora de Amortização</h1>
        <MortgageForm />
      </main>
    </>
  );
}
