import Head from "next/head";
import { Inter } from "next/font/google";
import { MortgageCalculator } from "@/ui-components/mortgage-calculator";


const inter = Inter({ subsets: ["latin"] });



export default function Home() {
  return (
    <>
      <Head>
        <meta charSet="utf-8"/>
        <title>Calculadora de Amortização</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`container ${inter.className}`}>
        <MortgageCalculator />
      </main>
    </>
  );
}
